# Generated by Django 3.2.3 on 2021-06-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writeup',
            field=models.CharField(default='0000000', max_length=2000),
        ),
    ]
