# Generated by Django 3.2.3 on 2021-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_writeup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='writeup',
            field=models.CharField(default='0000000', max_length=20000),
        ),
    ]
